<?php
declare(strict_types=1);
define('YC_BRIEFING_TEST_MODE',true);
require __DIR__.'/../briefing/internal/auto-route.php';
require __DIR__.'/../briefing/internal/notam.php';
require __DIR__.'/../briefing/engine.php';
$checks=0;
function check(bool $value,string $name): void {global $checks;$checks++;if(!$value)throw new RuntimeException('FAIL: '.$name);echo "PASS $name\n";}
foreach(new RecursiveIteratorIterator(new RecursiveDirectoryIterator(dirname(__DIR__))) as $file){if($file->isFile()&&$file->getExtension()==='php')token_get_all(file_get_contents($file->getPathname()),TOKEN_PARSE);}
check(true,'all PHP files parse');
$q=ycBriefQuality('great_circle',['raw'=>'AYT UM853 BUK','engine'=>'awc_fallback','unresolved'=>['AYT'],'pendingNavdata'=>[['token'=>'UM853']]],true);
check($q['state']==='fallback'&&$q['origin']==='automatic'&&$q['missingCount']===2,'HAR fallback cannot be labelled resolved navdata');
check(ycBn2RouteRefs(['routeMode'=>'great_circle','routeEngine'=>['navdataResolved'=>[['id'=>'UM853']]]],[])===[],'fallback has no candidate airway NOTAM references');
$d=ycBriefNavDetails(['extra_json'=>'{"c0type":"dme","c0channel":87,"c0channelsuffix":"X","c0pairedfreq":114000000,"c1type":"vor","c1frequency":114000000}']);
check(count($d['components'])===2&&$d['components'][0]['channel']==='87X'&&$d['components'][1]['frequencyText']==='114.000 MHz','VOR and DME components survive normalization');
$utc=new DateTimeZone('UTC');
$from=new DateTimeImmutable('2026-09-28 14:30',$utc);$to=$from->modify('+30 minutes');
check(ycBn2Schedule('MON 0800-1000 TUE 1400-1600',$from,$to)['relation']==='unknown','compound schedule never flattened across weekdays');
check(ycBn2Schedule('MON-FRI 0800-1000',$from,$to)['relation']==='inactive','simple inactive weekday range');
check(ycBn2Schedule('DAILY 1400-1600',$from,$to)['relation']==='active','active daily schedule');
check(ycBn2Schedule('DAILY 2900-3000',$from,$to)['relation']==='unknown','invalid schedule clock not clamped');
check(ycBn2Schedule('28 0800-1000',$from,$to)['relation']==='unknown','calendar dates not treated as daily');
check(ycBn2Schedule('MON 2300-0200',new DateTimeImmutable('2026-09-29 00:30',$utc),new DateTimeImmutable('2026-09-29 01:00',$utc))['relation']==='active','overnight schedule belongs to start weekday');
$points=ycBriefResample([[0,0],[0,.1],[0,10]],3);
check(abs($points[1][1]-5)<.001,'route sampling follows distance not vertex index');
$geometry=['type'=>'Point','coordinates'=>[5,0]];
$window=routeEncounterWindow([[0,0],[0,.1],[0,10]],$geometry,0,3600,20);
check($window!==null&&abs($window['etaClosest']-1800)<60,'SIGMET encounter ETA follows distance');
check(navFindRoutePath(['nodes'=>['A'=>['lat'=>0,'lon'=>0],'B'=>['lat'=>0,'lon'=>1]],'adj'=>[],'undirected'=>['A'=>[['next'=>'B']]]],'A','B',null,null)===null,'illegal reverse route is not accepted');
$rules=[['forward'=>1,'lower_text'=>'F085','upper_text'=>'F255','upper_unlimited'=>0,'status'=>'closed']];
check(ycBriefDirectionState($rules,200,true)==='closed'&&ycBriefDirectionState($rules,360,true)==='unknown','availability closure is level-specific');
check(ycBn2Vertical(['minimum_fl'=>null,'maximum_fl'=>null],360)['relation']==='unknown','unknown NOTAM band remains unknown');
$turns=[[0,0],[0,1],[1,1]];
$dense=ycBriefDensify($turns);
check(count(array_filter($dense,fn($p)=>abs($p[0])<1e-8&&abs($p[1]-1)<1e-8))===1,'densification preserves airway turns');
check(ycBn2GeometryDistance([[0,-1],[0,1]],['type'=>'MultiPoint','coordinates'=>[[0,-2],[0,2]]])>100,'MultiPoint does not invent connecting hazard line');
$db=new PDO('sqlite::memory:',null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$fields=['nms_id','series','number','year','notam_type','classification','affected_fir','location','icao_location','selection_code','traffic','purpose','scope','minimum_fl','maximum_fl','effective_start','effective_end','effective_end_raw','schedule','lower_limit','upper_limit','radius_nm','status','last_updated','notam_text','geometry','source','environment'];
$db->exec('CREATE TABLE notams ('.implode(',',array_map(fn($f)=>$f.' TEXT',$fields)).')');
$db->exec('CREATE TABLE notam_sync_state (source TEXT,environment TEXT,last_successful_sync TEXT)');
$db->sqliteCreateFunction('ST_AsGeoJSON',fn($v,$digits)=>$v,2);
$db->sqliteCreateFunction('ST_GeomFromText',fn($v)=>$v,1);
$db->sqliteCreateFunction('MBRIntersects',fn($a,$b)=>1,2);
$insert=$db->prepare('INSERT INTO notams (nms_id,icao_location,status,source,environment,notam_text) VALUES (?, ?, ?, ?, ?, ?)');
for($i=0;$i<85;$i++)$insert->execute([(string)$i,'LTAI','active',YC_NOTAM_SOURCE,YC_NOTAM_ENVIRONMENT,'RWY work']);
$payload=['routeMode'=>'great_circle','route'=>[[36.9,30.8],[52.36,13.5]],'flight'=>['etdUtc'=>'2026-09-26T18:50:00Z','estimatedArrivalUtc'=>'2026-09-26T21:47:00Z','cruiseFL'=>360]];
$impact=ycBn2Enrich($payload,['from'=>'LTAI','to'=>'EDDB'],$db)['notamImpact'];
check($impact['matchedCount']===85&&$impact['shownCount']===80&&$impact['itemsTruncated'],'NOTAM totals survive display cap');
check($impact['unknownLevelCount']===85&&$impact['atCruiseLevelCount']===0,'unknown levels never inflate cruise matches');
check($impact['coverageComplete']===false&&$impact['sourceFreshness']==='unknown','missing sync cannot claim complete coverage');
$db->exec("UPDATE notams SET effective_end='2026-09-26 18:00:00' WHERE nms_id='0'");
$impact=ycBn2Enrich($payload,['from'=>'LTAI','to'=>'EDDB'],$db)['notamImpact'];
check($impact['matchedCount']===85,'departure window includes validity ending before ETD within 90 minutes');
$db->exec("UPDATE notams SET effective_end='2026-09-26 16:00:00' WHERE nms_id='0'");
$impact=ycBn2Enrich($payload,['from'=>'LTAI','to'=>'EDDB'],$db)['notamImpact'];
check($impact['matchedCount']===84,'records outside endpoint validity window are excluded');
$cacheQuery=['format'=>'json','ids'=>'TEST'];ksort($cacheQuery);
$cacheKey='awc|'.AWC_BASE.'metar?'.http_build_query($cacheQuery,'','&',PHP_QUERY_RFC3986);
ycBriefCacheWrite($cacheKey,['ok'=>true,'status'=>200,'data'=>[['icaoId'=>'TEST']],'retrievedAt'=>'2026-09-26T18:00:00Z']);
$cached=awcGetMany([['path'=>'metar','query'=>$cacheQuery]]);
check($cached[0]['data'][0]['icaoId']==='TEST'&&$cached[0]['retrievedAt']==='2026-09-26T18:00:00Z','source cache preserves retrieval time');
$database=getenv('YC_AUDIT_DB');
if($database&&is_file($database)){
    $pdo=new PDO('sqlite:'.$database,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
    $route=resolveUserRoute('AYT UM853 BUK UM861 RAKUR M856 ROMOK M861 KIV M860 INROG L981 ADVAB L980 SUBIX','LTAI','EDDB',['lat'=>36.8979,'lon'=>30.8009],['lat'=>52.3626,'lon'=>13.5039],$pdo);
    check($route['engine']==='mariadb_navdata','real dump resolver uses navdata');
    check($route['unresolved']===[],'eight HAR unresolved points exist and resolve');
    check(count($route['navdataResolved'])===7,'all seven HAR airways resolve');
    check($route['pendingNavdata']===[],'no pending airway after connection fix');
    check(count($route['route'])>2&&$route['distanceNm']>1180,'actual route geometry replaces direct line');
    check(count(array_filter($route['resolved'],fn($r)=>$r['id']==='AYT'&&count($r['details']['components']??[])===2))>0,'AYT VOR/DME reaches route output');
    if(getenv('YC_AUDIT_OUT'))file_put_contents(getenv('YC_AUDIT_OUT'),json_encode($route,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT));
    echo 'ROUTE '.count($route['route']).' vertices, '.round($route['distanceNm'])." NM\n";
}else echo "SKIP real-dump integration (set YC_AUDIT_DB)\n";
echo "OK $checks checks\n";
