<?php
declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
header('X-Content-Type-Options: nosniff');
header('Cache-Control: no-store, max-age=0');
header('X-YC-API-Resource: notam');

function out(int $status,array $payload):never{http_response_code($status);echo json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
if(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET'))!=='GET'){header('Allow: GET');out(405,['ok'=>false,'error'=>'HTTP method not allowed.']);}

function db():PDO{
 static $pdo=null;if($pdo instanceof PDO)return $pdo;
 $path=dirname(__DIR__,3).'/data.php';if(!is_file($path))out(500,['ok'=>false,'error'=>'Veritabanı yapılandırması bulunamadı.']);
 $c=require $path;if(!is_array($c))out(500,['ok'=>false,'error'=>'Veritabanı yapılandırması geçersiz.']);
 try{$pdo=new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',$c['host'],(int)$c['port'],$c['database']),$c['user'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
 catch(Throwable $e){error_log('[notam-db] '.$e->getMessage());out(500,['ok'=>false,'error'=>'Veritabanına bağlanılamadı.']);}return $pdo;
}
function utc(?string $v):DateTimeImmutable{try{return(trim((string)$v)===''?new DateTimeImmutable('now',new DateTimeZone('UTC')):new DateTimeImmutable((string)$v,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('UTC'));}catch(Throwable){out(400,['ok'=>false,'error'=>'Geçersiz UTC zamanı.']);}}
function ident(array $r):string{$s=strtoupper(trim((string)($r['series']??'')));$n=trim((string)($r['number']??''));$y=trim((string)($r['year']??''));if($s===''&&$n==='')return(string)($r['nms_id']??'');$v=$s.$n;if($y!==''&&!preg_match('/\/\d{2}$/',$v))$v.='/'.substr($y,-2);return$v;}
function cols(bool $text=true,bool $geo=false):string{$a=['n.nms_id','n.series','n.number','n.year','n.notam_type','n.classification','n.affected_fir','n.location','n.icao_location','n.account_id','n.selection_code','n.traffic','n.purpose','n.scope','n.minimum_fl','n.maximum_fl','n.effective_start','n.effective_end','n.effective_end_raw','n.estimated','n.schedule','n.lower_limit','n.upper_limit','n.coordinates_raw','n.radius_nm','n.status','n.last_updated'];if($text)$a[]='n.notam_text';if($geo)$a[]='ST_AsGeoJSON(n.geometry,6) AS geometry';return implode(',',$a);}
function item(array $r,bool $text=true):array{$x=['id'=>(string)($r['nms_id']??''),'ident'=>ident($r),'type'=>$r['notam_type']??null,'classification'=>$r['classification']??null,'fir'=>$r['affected_fir']??null,'location'=>$r['location']??null,'icaoLocation'=>$r['icao_location']??null,'selectionCode'=>$r['selection_code']??null,'traffic'=>$r['traffic']??null,'purpose'=>$r['purpose']??null,'scope'=>$r['scope']??null,'minimumFl'=>isset($r['minimum_fl'])?(int)$r['minimum_fl']:null,'maximumFl'=>isset($r['maximum_fl'])?(int)$r['maximum_fl']:null,'effectiveStart'=>$r['effective_start']??null,'effectiveEnd'=>$r['effective_end']??null,'effectiveEndRaw'=>$r['effective_end_raw']??null,'schedule'=>$r['schedule']??null,'lowerLimit'=>$r['lower_limit']??null,'upperLimit'=>$r['upper_limit']??null,'coordinates'=>$r['coordinates_raw']??null,'radiusNm'=>isset($r['radius_nm'])?(float)$r['radius_nm']:null,'status'=>$r['status']??null,'lastUpdated'=>$r['last_updated']??null];if($text)$x['text']=$r['notam_text']??null;return$x;}
function temporal(array $r,DateTimeImmutable $at):string{if(strtolower((string)($r['status']??''))==='cancelled')return'cancelled';$t=$at->getTimestamp();$s=!empty($r['effective_start'])?strtotime($r['effective_start'].' UTC'):false;$e=!empty($r['effective_end'])?strtotime($r['effective_end'].' UTC'):false;if($s!==false&&$s>$t)return'future';if(strtoupper((string)($r['effective_end_raw']??''))!=='PERM'&&$e!==false&&$e<$t)return'expired';return'valid';}
function addIn(array &$w,array &$p,string $column,string $prefix,string $raw,string $regex):void{$vals=[];foreach(explode(',',$raw)as$v){$v=strtoupper(trim($v));if($v!==''&&preg_match($regex,$v))$vals[]=$v;}if(!$vals)return;$h=[];foreach(array_slice(array_unique($vals),0,20)as$i=>$v){$k=$prefix.$i;$h[]=':'.$k;$p[$k]=$v;}$w[]=$column.' IN ('.implode(',',$h).')';}

function listAction(PDO $pdo):never{
 $at=utc($_GET['at']??null);$state=strtolower(trim((string)($_GET['state']??'valid')));if(!in_array($state,['valid','future','expired','cancelled','all'],true))$state='valid';$page=max(1,(int)($_GET['page']??1));$limit=max(1,min(200,(int)($_GET['limit']??50)));$offset=($page-1)*$limit;$where=["n.source='FAA_NMS'","n.environment='production'"];$p=[];$t=$at->format('Y-m-d H:i:s');
 if($state==='valid'){$where[]="n.status<>'cancelled'";$where[]='(n.effective_start IS NULL OR n.effective_start<=:a1)';$where[]="(UPPER(COALESCE(n.effective_end_raw,''))='PERM' OR n.effective_end IS NULL OR n.effective_end>=:a2)";$p['a1']=$t;$p['a2']=$t;}elseif($state==='future'){$where[]="n.status<>'cancelled'";$where[]='n.effective_start>:a1';$p['a1']=$t;}elseif($state==='expired'){$where[]="n.status<>'cancelled'";$where[]="UPPER(COALESCE(n.effective_end_raw,''))<>'PERM'";$where[]='n.effective_end<:a1';$p['a1']=$t;}elseif($state==='cancelled')$where[]="n.status='cancelled'";
 $icao=strtoupper(trim((string)($_GET['icao']??'')));if(preg_match('/^[A-Z0-9]{4}$/',$icao)){$where[]="(UPPER(COALESCE(n.icao_location,''))=:icao OR UPPER(COALESCE(n.location,''))=:loc)";$p['icao']=$icao;$p['loc']=$icao;}
 addIn($where,$p,"UPPER(COALESCE(n.affected_fir,''))",'f',(string)($_GET['fir']??''),'/^[A-Z0-9]{4}$/');addIn($where,$p,"UPPER(COALESCE(n.notam_type,''))",'t',(string)($_GET['type']??''),'/^[A-Z]{1,4}$/');addIn($where,$p,"UPPER(COALESCE(n.classification,''))",'c',(string)($_GET['classification']??''),'/^[A-Z0-9_ -]{1,40}$/');addIn($where,$p,"UPPER(COALESCE(n.scope,''))",'s',(string)($_GET['scope']??''),'/^[A-Z]{1,8}$/');addIn($where,$p,"UPPER(COALESCE(n.traffic,''))",'tr',(string)($_GET['traffic']??''),'/^[A-Z]{1,8}$/');
 $q=trim((string)($_GET['q']??''));if($q!==''){$where[]='(n.nms_id LIKE :q OR n.notam_text LIKE :q2 OR n.selection_code LIKE :q3)';$p['q']='%'.$q.'%';$p['q2']='%'.$q.'%';$p['q3']='%'.$q.'%';}
 $ws=implode(' AND ',$where);$cs=$pdo->prepare('SELECT COUNT(*) FROM notams n WHERE '.$ws);$cs->execute($p);$total=(int)$cs->fetchColumn();$order=match((string)($_GET['sort']??'updated_desc')){'start_desc'=>'n.effective_start DESC','start_asc'=>'n.effective_start ASC','ident'=>'n.series,n.number,n.year DESC',default=>'n.last_updated DESC'};$st=$pdo->prepare('SELECT '.cols(true,false).' FROM notams n WHERE '.$ws.' ORDER BY '.$order.' LIMIT '.$limit.' OFFSET '.$offset);$st->execute($p);$items=[];while($r=$st->fetch()){$x=item($r,true);$x['temporalState']=temporal($r,$at);$items[]=$x;}$pages=$total?(int)ceil($total/$limit):0;out(200,['ok'=>true,'source'=>'FAA NMS','state'=>$state,'atUtc'=>$at->format('c'),'items'=>$items,'paging'=>['page'=>$page,'limit'=>$limit,'returned'=>count($items),'total'=>$total,'pages'=>$pages,'hasPrevious'=>$page>1,'hasNext'=>$pages>0&&$page<$pages]]);
}
function filtersAction(PDO $pdo):never{$o=[];foreach(['type'=>'notam_type','classification'=>'classification','scope'=>'scope','traffic'=>'traffic']as$k=>$c){$s=$pdo->query("SELECT DISTINCT {$c} value FROM notams WHERE source='FAA_NMS' AND environment='production' AND {$c} IS NOT NULL AND {$c}<>'' ORDER BY {$c} LIMIT 200");$o[$k]=array_values(array_filter(array_column($s->fetchAll(),'value')));}out(200,['ok'=>true,'source'=>'FAA NMS','options'=>$o]);}
function detailAction(PDO $pdo):never{$id=trim((string)($_GET['id']??''));if($id==='')out(400,['ok'=>false,'error'=>'NOTAM id gerekli.']);$s=$pdo->prepare('SELECT '.cols(true,false)." FROM notams n WHERE n.source='FAA_NMS' AND n.environment='production' AND n.nms_id=:id LIMIT 1");$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r)out(404,['ok'=>false,'error'=>'NOTAM bulunamadı.']);out(200,['ok'=>true,'source'=>'FAA NMS','notam'=>item($r,true)]);}

function normLon(float $v):float{while($v>180)$v-=360;while($v<-180)$v+=360;return$v;}
function bbox(float $w,float $s,float $e,float $n,array &$p,string $g):string{if($w<=$e){$p['bbox']=sprintf('POLYGON((%.8F %.8F,%.8F %.8F,%.8F %.8F,%.8F %.8F,%.8F %.8F))',$w,$s,$e,$s,$e,$n,$w,$n,$w,$s);return"MBRIntersects({$g},ST_GeomFromText(:bbox))";}$p['b1']=sprintf('POLYGON((%.8F %.8F,180 %.8F,180 %.8F,%.8F %.8F,%.8F %.8F))',$w,$s,$s,$n,$w,$n,$w,$s);$p['b2']=sprintf('POLYGON((-180 %.8F,%.8F %.8F,%.8F %.8F,-180 %.8F,-180 %.8F))',$s,$e,$s,$e,$n,$n,$s);return"(MBRIntersects({$g},ST_GeomFromText(:b1)) OR MBRIntersects({$g},ST_GeomFromText(:b2)))";}
function semantic(array $r):array{$q=strtoupper((string)($r['selection_code']??''));$sub=preg_match('/^Q([A-Z]{2})/',$q,$m)?$m[1]:'';$class=match($sub){'RD','RP','RR','RT'=>'RESTRICTED_AIRSPACE','WY'=>'AERIAL_SURVEY','WE'=>'EXERCISE','WF'=>'AIR_REFUELING','WM'=>'FIRING','WU'=>'UAV_ACTIVITY','WG','WL','WP','WT'=>'AERIAL_SPORT_ACTIVITY','OB'=>'OBSTACLE','MR'=>'RUNWAY',default=>'OTHER'};$group=match($sub){'WG','WL','WP','WT'=>'AERIAL_SPORT','RD','RP','RR','RT'=>'RESTRICTED_AIRSPACE','WY'=>'AERIAL_SURVEY','WE','WF','WM','WU'=>'TRAINING_MILITARY',default=>'OTHER'};return[$class,$group];}
function parseCoord(string $v):?array{$v=strtoupper(trim($v));if(preg_match('/^([0-9]{2})([0-9]{2})([NS])([0-9]{3})([0-9]{2})([EW])$/',$v,$m)){$lat=(float)$m[1]+(float)$m[2]/60;$lon=(float)$m[4]+(float)$m[5]/60;if($m[3]==='S')$lat*=-1;if($m[6]==='W')$lon*=-1;return[$lon,$lat];}return null;}
function feature(array $r,array $g,string $source,string $accuracy):array{[$class,$group]=semantic($r);return['type'=>'Feature','geometry'=>$g,'properties'=>['layer'=>'notam','nms_id'=>(string)$r['nms_id'],'ident'=>ident($r),'classification'=>$r['classification']??null,'location'=>$r['location']??null,'icao_location'=>$r['icao_location']??null,'selection_code'=>$r['selection_code']??null,'traffic'=>$r['traffic']??null,'purpose'=>$r['purpose']??null,'scope'=>$r['scope']??null,'effective_start'=>$r['effective_start']??null,'effective_end'=>$r['effective_end']??null,'effective_end_raw'=>$r['effective_end_raw']??null,'lower_limit'=>$r['lower_limit']??null,'upper_limit'=>$r['upper_limit']??null,'semantic_class'=>$class,'display_group'=>$group,'geometry_source'=>$source,'geometry_accuracy'=>$accuracy]];}
function mapAction(PDO $pdo):never{
 foreach(['west','south','east','north']as$k)if(!isset($_GET[$k])||!is_numeric($_GET[$k]))out(400,['ok'=>false,'error'=>'Eksik/geçersiz bbox.']);$w=normLon((float)$_GET['west']);$e=normLon((float)$_GET['east']);$s=max(-85,min(85,(float)$_GET['south']));$n=max(-85,min(85,(float)$_GET['north']));if($s>$n)[$s,$n]=[$n,$s];$z=max(0,min(18,(int)($_GET['z']??5)));$at=utc($_GET['at']??null);if($z<5)out(200,['ok'=>true,'source'=>'FAA NMS','atUtc'=>$at->format('c'),'data'=>['type'=>'FeatureCollection','features'=>[]],'counts'=>['notam'=>0],'truncated'=>false]);$time=$at->format('Y-m-d H:i:s');$base="n.source='FAA_NMS' AND n.environment='production' AND n.status<>'cancelled' AND (n.effective_start IS NULL OR n.effective_start<=:a1) AND (UPPER(COALESCE(n.effective_end_raw,''))='PERM' OR n.effective_end IS NULL OR n.effective_end>=:a2)";$p=['a1'=>$time,'a2'=>$time];$bs=bbox($w,$s,$e,$n,$p,'n.geometry');$st=$pdo->prepare('SELECT '.cols(true,true).' FROM notams n WHERE '.$base.' AND n.geometry IS NOT NULL AND '.$bs.' ORDER BY n.last_updated DESC LIMIT 5000');$st->execute($p);$f=[];$seen=[];while($r=$st->fetch()){$g=json_decode((string)$r['geometry'],true);if(!is_array($g))continue;$f[]=feature($r,$g,'faa-geometry','AUTHORITATIVE');$seen[(string)$r['nms_id']]=true;}$tr=count($f)>=5000;
 $ap=$pdo->prepare("SELECT ident,lat,lon FROM nav_points WHERE kind='airport' AND lat BETWEEN :s AND :n AND ".($w<=$e?'lon BETWEEN :w AND :e':'(lon>=:w OR lon<=:e)'));$ap->execute(['s'=>$s,'n'=>$n,'w'=>$w,'e'=>$e]);$air=[];foreach($ap as$r)$air[strtoupper($r['ident'])]=[(float)$r['lon'],(float)$r['lat']];if($air){$ids=array_keys($air);$h=[];$pp=['a1'=>$time,'a2'=>$time];foreach($ids as$i=>$v){$k='i'.$i;$h[]=':'.$k;$pp[$k]=$v;}$ns=$pdo->prepare('SELECT '.cols(true,false).' FROM notams n WHERE '.$base." AND n.geometry IS NULL AND (UPPER(COALESCE(n.icao_location,'')) IN (".implode(',',$h).") OR UPPER(COALESCE(n.location,'')) IN (".implode(',',$h).')) LIMIT 4000');$ns->execute($pp);foreach($ns as$r){$id=(string)$r['nms_id'];if(isset($seen[$id]))continue;$code=strtoupper((string)($r['icao_location']?:$r['location']));if(isset($air[$code])){$f[]=feature($r,['type'=>'Point','coordinates'=>$air[$code]],'airport-location','APPROXIMATE');$seen[$id]=true;}}}
 out(200,['ok'=>true,'source'=>'FAA NMS','environment'=>'production','atUtc'=>$at->format('c'),'data'=>['type'=>'FeatureCollection','features'=>$f],'counts'=>['notam'=>count($f)],'truncated'=>$tr]);
}

try{$pdo=db();$a=strtolower(trim((string)($_GET['action']??'list')));if($a==='list')listAction($pdo);if($a==='filters')filtersAction($pdo);if($a==='detail')detailAction($pdo);if($a==='map')mapAction($pdo);if($a==='health'){$c=(int)$pdo->query("SELECT COUNT(*) FROM notams WHERE source='FAA_NMS' AND environment='production'")->fetchColumn();out(200,['ok'=>true,'resource'=>'notam','records'=>$c]);}out(400,['ok'=>false,'error'=>'Bilinmeyen NOTAM action.']);}catch(Throwable $e){error_log('[notam] '.$e->getMessage());out(500,['ok'=>false,'error'=>'NOTAM isteği işlenemedi.']);}
